# Step 5 Github Environment Variables
name: CI/CD Pipeline

on:
  push:
  
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy
        run: npm deploy

# Step 4 Creating a Workflow with Multiple Jobs
# name: CI/CD Pipeline

# on: [push]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3
#     - name: Install Dependencies
#       run: npm install
#     - name: Run tests
#       run: npm test

#   deploy:
#     needs: test
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3
#     - name: Deploy
#       run: npm deploy

# Step 3 Adding Deployment Stages
# name: CI/CD

# on:
#   push:
  
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Install Dependencies
#         run: npm install
#       - name: Run tests
#         run: npm test

#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy
#         run: npm deploy

# Step 2 Adding Testing Stages
# name: CI

# on: [push]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3
#     - name: Install Dependencies
#       run: npm install
#     - name: Run tests
#       run: npm test


# Step 1 Setting up a Simple Workflow
# name: CI

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

# Original code
# name: Run mandatory tests
# on: pull_request
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install modules
#       run: npm install
#     - name: Run mandatory tests
#       run: npm test -- --selectProjects mandatory

